services:
  firefly-bot:
    build: .
    container_name: firefly_bot
    command: python run.py
    env_file:
      - .env
    networks:
      - firefly_net
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=false

networks:
  firefly_net:
    external: true
    name: fireflyiii_firefly_iii