from telegram.ext import ConversationHandler

# Conversation states for expense flow
SELECT_ORIGIN, ENTER_AMOUNT_DESC, SELECT_DESTINATION, ENTER_NEW_DEST_NAME = range(4)
SELECT_CATEGORY, SELECT_BUDGET, SELECT_BILL, ENTER_TAGS, CONFIRM_EXPENSE = range(4, 9)

# Conversation states for transfer flow
TRANSFER_ENTER_AMOUNT, TRANSFER_SELECT_SOURCE, TRANSFER_SELECT_DESTINATION, TRANSFER_CONFIRM = range(9, 13)
