name: Release Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (example: v1.0.0)'
        required: true
      body:
        description: 'Release notes (changelog)'
        required: true

jobs:
  create-release:
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Create Git Tag
        run: |
          git tag ${{ github.event.inputs.version }}
          git push origin ${{ github.event.inputs.version }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: Release ${{ github.event.inputs.version }}
          body: ${{ github.event.inputs.body }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger Build and Push Docker Workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: docker-publish.yml
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: refs/heads/main
          inputs: '{"custom_tag": "${{ github.event.inputs.version }}"}'